### ISSUE TITLE
First, Focus on the Problem

### ISSUE THREAD

**Issue by roughani** [code4sac/ndoch-2016#1]
### Focus on the Problem

Hackathons work best when focused on a specific problem set. Want to do a hackathon about crime? Better call the police department. Want to do something around housing? Recruit somebody from the local housing authority or somebody who runs a shelter. When trying to think about the needs and challenges of the front line, there’s no substitute for somebody who actually works in that space to speak at your event and to help you identify the right problems to be solved.
- [x] Decide on one or two _themes_ for your event
- [x] Identify potential problem areas within these themes to set a "problem context" 
- [x] Once identified, move on to recruiting SME's/Stakeholders to help you better understand the problems within the themes/problem context (#4)

**Comment by joelrip** [comment]
Attending:
Mayor (confirm)
SHRA (Tyrone Roderick-Williams for Sat, Geoff Ross for Wed)
Maria McGunigal
Abhi Nemani

Still talking:
Christine Tien
Deb Marois
Doris Matsui
