### ISSUE TITLE
Develop an Agenda

### ISSUE THREAD

**Issue by roughani** [code4sac/ndoch-2016#2]
### Develop an Agenda

Your agenda will vary depending on the goal of your hackathon and it’s something that you should determine early on in your planning.

There’s a temptation to have hackathons become two day sprints with participants getting little to no sleep. However, if the goal of the hackathon is to develop prototypes versus fully working apps, you may not need really need to make a coffee run at 2 in the morning.
#### One Day Hackathon Example
- 7:00am Event organizers arrive to help set up
- 7:30am Food/Coffee/Water arrives
- 8:00am Breakfast
- 8:30am Welcome (“Hi, welcome! Here’s the wifi password, the bathrooms are over there.”)
- 8:45am Education (“Here’s what we’ve done so far, here are some resources”) [You can also cover this in a pre-event email]
- 9:00am Problem Set (“Here’s the problem I’m facing in the day-to-day”) [You can also cover this in a pre-event email]
- 10:00am Q & A (“Would this be helpful?” “How does this activity work?”)
- 10:15am Break out to form teams and hack! (If using Hackshop format for attendees, begin facilitation of Hackshop format alongside the attendee guide at http://hackshop.waffle.io)
- 12:00pm Lunch served
- 4:00pm Hacking ends, judging begins (if applicable)
- 4:30pm Project winners announced (If applicable)

Variations on this include having the talking portion of the event happen on a Friday night. (This is particularly helpful if you’re trying to have working prototypes by the end of the event.) This allows for a full day (or full two days) of hack time.
#### Two Day Hackshop Example

_See [The Hackshop Playbook](https://github.com/waffleio/hackshop-playbook) for more information and resources._

_Day One_
- 6:00 pm - Welcome Dinner & Networking 
- 6:30 pm - Introductions to organizers and specialists from the field 
- 6:45 pm - Overview of event goals
- 7:00 pm - Problem Pitching - What Problem do _you_ want to Solve? 
- 7:30 pm - Team Formation 
- 8:00 pm - Getting Started with Waffle & GitHub 
- 8:30 pm - Lean Canvas & Hackshop introduction
- 9:00 pm - Team Sprint 1 (Customer/Problem/Promise) (45 minutes)
- 9:45 pm - Wrap up 

_Day Two_
- 8:30 am - Breakfast, Hackshop intervention: Lean Canvas Review 
- 9:00 am - Team Sprint 2 (problem/solution) (1 hr) 
- 10:00 am - Customer Advisor/Feedback Panel
- 10:45 am - Hackshop Lesson: Iterate/Pivot/Persevere
- 11:00 am - Team Sprint 3 - Adjust Canvas (30 minutes) 
- 11:30 pm - Hackshop Lesson: Running Lightweight Experiments
- 12:00 pm - Lunch 
- 12:00 pm - Team Sprint 4 begins (1 hr)
- 1:00 pm - Hackshop intervention: Review team experiments 
- 1:30 pm - Team Sprint 5 (build) (2 hrs) 
- 3:00 pm - Hackshop lesson: How to build your pitch 
- 3:30 pm - 30 Minute warning/tech test 
- 4:00 pm - Pitches Begin 
- 4:30 pm - Judging & Prizes 
#### unConference Example
- 7:00am Event organizers arrive to help set up.
- 7:30am Food/Coffee/Water arrives
- 8:00am Breakfast
- 8:30am Welcome (“Hi, welcome! Here’s the wifi password, the bathrooms are over there.”)
- 8:45am unConference 101 (“Here’s how unconferences work”)
- 9:00am Icebreaker (“Everyone is going to form a line based on a statement. If you agree head to the right, disagree head to the left. OK, the weather is too cold!”)
- 9:30am Throw session ideas on the board, vote, assign rooms
- 10:00am First Session
- 11:00am Second Session
- 12:00pm Lunch served (Throw out and vote on afternoon sessions)
- 1:00pm Third Session
- 2:00pm Forth Session
- 3:00pm Group Returns & Report backs (Here’s what we talked about)

*\* These are just general examples and in the course of running the event you may find yourself running a bit behind. We always assume that things are going to run over by about 15 mins and just prepare accordingly. (You can use the lunch hour to make up for time.)

**Comment by joelrip** [comment]
8:00am Event organizers arrive to help set up
8:30am Food/Coffee/Water arrives
9:00am Breakfast/nametags/mingle
9:30am Welcome from Joel (“Hi, welcome! Here’s the wifi password, the bathrooms are over there.”)
9:40am Mayor Johnson announces RAILS grants
9:50am Joel on PZ
9:55am SHRA
10:05am Christine Tien
10:15am Maria McGunigal
10:20am Joel on available tools and agenda for the day
10:30am Q & A (“Would this be helpful?” “How does this activity work?”)
10:45am Break out to form teams and hack! (If using Hackshop format for attendees, begin facilitation of Hackshop format alongside the attendee guide at http://hackshop.waffle.io)
12:00pm Lunch served
4:00pm Hacking ends, judging begins (if applicable)
4:30pm Project winners announced (If applicable)

**Comment by roughani** [comment]
@joelrip Eventbrite and Meetup have the event starting at 10am. So either the agenda or the event pages need to be updated accordingly.

**Comment by joelrip** [comment]
I know. I was hypothesizing an earlier start to allow for more coding time.
Your thoughts welcome.

**Comment by roughani** [comment]
I'm fairly indifferent at this point, but I'm not sure it makes sense to change the official start time on the event pages. So maybe the best move is to add a high-level agenda to the event pages, send a reminder email to registrants, and clarify that check-in/breakfast/nametags/mingle begins at 9:30 with the event starting promptly at 10:00. In any case, I think more time for coding is better achieved by changing the end time. There's actually no extra time in this agenda given that the event pages specify 10-6.

If you can settle the timing issue for us, I'll take the lead on adding the challenge language + Ethos logo to the event pages and hitting the announce button on Meetup. We're 2 weeks out and really ought to hit the gas on marketing soon.

**Comment by sactomaya** [comment]
Will send initial email in the morning.  Was hoping to hear from Christine
Tien. Will pull the trigger and keep fingers crossed.
On May 19, 2016 11:08 PM, "Ash Roughani" notifications@github.com wrote:

I'm fairly indifferent at this point, but I'm not sure it makes sense to
change the official start time on the event pages. So maybe the best move
is to add a high-level agenda to the event pages, send a reminder email to
registrants, and clarify that check-in/breakfast/nametags/mingle begins at
9:30 with the event starting promptly at 10:00. In any case, I think more
time for coding is better achieved by changing the end time. There's
actually no extra time in this agenda given that the event pages specify
10-6.

If you can settle the timing issue for us, I'll take the lead on adding the
challenge language + Ethos logo to the event pages and hitting the announce
button on Meetup. We're 2 weeks out and really ought to hit the gas on
marketing soon.

**Comment by joelrip** [comment]
@roughani Fair enough. I was just drafting edits to the "one day hackathon example" in this issue, and hadn't bothered with the end time yet.  Probably something like below then (obviously we share only high level agenda at this point as speakers are unconfirmed).

8:30am Event organizers arrive to help set up
9:00am Food/Coffee/Water arrives
9:30am Breakfast/nametags/mingle
10:00am Welcome from Joel (“Hi, welcome! Here’s the wifi password, the bathrooms are over there.”)
10:05am Mayor Johnson announces RAILS grants
10:15am SHRA on PZ
10:25am Christine Tien
10:35am Maria McGunigal
10:40am Joel on available tools and agenda for the rest of the day
10:50am Q & A (“Would this be helpful?” “How does this activity work?”)
11:00am Break out to form teams and hack!
12:00pm Lunch served
5:00pm Hacking ends, begin presentations/demos
5:30pm Judges deliberate
5:45pm Announce winners

But let's also advertise the Wednesday meetup as the opportunity for teams to form and learn more about the challenge. I'm talking to SHRA at noon today and will pitch them on being there for Hack Night. If not them, maybe we can wrangle the HUD rep who's coming to town (will learn more about them today). I'll change the meetup description now.

**Comment by joelrip** [comment]
@sactomaya We do need to send something out immediately if you haven't already, but don't advertise that people will be there if we haven't talked to them yet.

**Comment by sactomaya** [comment]
@joelrip @roughani I'm not finding the mailchimp login info.

**Comment by joelrip** [comment]
I've just added you to the Code for Sac Executive Team folder. All
passwords are there. Use them wisely.

**Comment by joelrip** [comment]
@roughani Looped you in on the convo with SHRA, so you can see what went on there today. Good involvement from them. Yes, please do update the event pages and announce as appropriate.

@sactomaya will send out an email blast as well.

**Comment by roughani** [comment]
I've changed the last part of the agenda as follows:

5:00pm Hacking ends, begin presentations/demos
5:30pm Judges deliberate
5:45pm Announce winners

**Comment by roughani** [comment]
If someone could announce the meetup on Monday morning, that would be ideal timing to continue the momentum. Also consider inviting friends to the Facebook event with an emphasis on a need for subject matter experts (to avoid the "I'm not a coder" reaction). 

At this point, I will have very little bandwidth to promote via Code for Sac channels. Instead I'll be working the city angles internally. For example, there will be a blurb in the Mayor's next email newsletter. And I obviously can't be compensated for my time as a Code for Sac organizer, as that teeters on conflict of interest.

**Comment by sactomaya** [comment]
Just got done with the memorial service. I'll be pushing this for the rest
of the time. We also enlisted the SHRA VISTAs' help.

Curious about media. Should I just talk to Ben?

**Comment by sactomaya** [comment]
Yo, Deb Marois is planning to come on Weds and Saturday - can speak to some of the PZ partners' needs based on UCD eval work

**Comment by roughani** [comment]
Is this where the final agenda lives? If not, please send me a link to the latest version.

**Comment by joelrip** [comment]
Final agenda:

Saturday, June 4
9:30am Coffee, attendee arrival
10:00am Welcome by Joel
10:03am Welcome by Brandon Weber
10:05am Announcement of City RAILS grants by Mayor Kevin Johnson
10:15am Quick orientation to the day's event by Joel
10:20am Discussion of Promise Zones by Tyrone Roderick-Williams
10:25am CHHS on CA challenges
10:30am Deb Marois on performance measurement and evaluation
10:35am Maria McGunigal on City open data
10:40am Joel on available data and tools
10:45am Q&A
11:00am Intros by members looking for teams, team formation, hacking!
5:00pm Presentations/demos by teams
5:45pm Judging (Maria McGunigal, Lynnette McRae, Deb Marois, Abhi Nemani)
6:00pm Prize awarded

**Comment by roughani** [comment]
Where should we slot Abhi in?

**Comment by joelrip** [comment]
I'm thinking right after MKJ? Transition from City's initiative, through the Innovation Office, to what we're doing today.
